name: download
on:
  schedule:
    - cron: '0 6,18 * * *'
  workflow_dispatch:

jobs:
  update:
    name: Update
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Run
        run: sh download_json.sh
        shell: bash

      - name: Commit
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "actions@github.com"
          git config pull.rebase false
          git status
          git pull origin $GITHUB_REF
          git add ./data/
          git commit -m "Adding new wildfire files" && git push || true
        shell: bash
