name: Scrape latest data

on:
  push:
  workflow_dispatch:
  schedule:
    - cron:  '6 18 * * *'

jobs:
  scheduled:
    runs-on: ubuntu-latest
    steps:
    - name: Check out this repo
      uses: actions/checkout@v2
    - name: Fetch latest data
      run: |-
        timestamp=$(date '+%Y-%m-%d_%H:%M:%S')
        curl 'https://opendata.arcgis.com/datasets/5da472c6d27b4b67970acc7b5044c862_0.geojson' | jq . > "data/wildfires_${timestamp}_UTC.json"
    - name: Commit and push if it changed
      run: |-
        git config user.name "Automated"
        git config user.email "actions@users.noreply.github.com"
        git add -A
        timestamp=$(date -u)
        git commit -m "Latest data: ${timestamp}" || exit 0
        git push
