name: Scrape latest data

on:
  push:
  workflow_dispatch:
  schedule:
    - cron:  '6 6,18 * * *'

jobs:
  scheduled:
    runs-on: ubuntu-latest
    steps:
    - name: Check out this repo
      uses: actions/checkout@v2
    - name: Fetch latest data
      run: |-
        timestamp=$(date '+%Y-%m-%d_%H:%M:%S')
        curl 'https://services3.arcgis.com/T4QMspbfLg3qTGWY/ArcGIS/rest/services/Public_Wildfire_Perimeters_View/FeatureServer/0/query?f=json&returnGeometry=true&outFields=*&where=1=1' | jq . > "data/wildfires_$timestamp_UTC.json"
    - name: Commit and push if it changed
      run: |-
        git config user.name "Automated"
        git config user.email "actions@users.noreply.github.com"
        git add -A
        timestamp=$(date -u)
        git commit -m "Latest data: ${timestamp}" || exit 0
        git push
